
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '&&)\x07-\x9f\xa8\xe4\xe2\x1e\\\x16\xe8\x99\xa0j'
    
_lr_action_items = {'RELOP':([5,6,8,13,],[-11,9,9,9,]),'OPBR':([7,10,15,16,17,18,],[10,10,10,10,10,10,]),'EQUALS':([3,],[7,]),'MINUS':([11,12,14,19,20,21,22,23,],[-8,17,17,-7,17,17,17,17,]),'CLBR':([11,14,19,20,21,22,23,],[-8,19,-7,-3,-6,-5,-4,]),'WHILE':([0,],[2,]),'PLUS':([11,12,14,19,20,21,22,23,],[-8,15,15,-7,15,15,15,15,]),'DIV':([11,12,14,19,20,21,22,23,],[-8,16,16,-7,16,16,16,16,]),'IF':([0,],[4,]),'ID':([0,2,4,7,9,10,15,16,17,18,],[3,5,5,11,5,11,11,11,11,11,]),'MULT':([11,12,14,19,20,21,22,23,],[-8,18,18,-7,18,18,18,18,]),'$end':([1,3,5,6,8,11,12,13,19,20,21,22,23,],[0,-2,-11,-12,-9,-8,-1,-10,-7,-3,-6,-5,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'boo':([2,4,9,],[6,8,13,]),'expression':([7,10,15,16,17,18,],[12,14,20,21,22,23,]),'sentence':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> ID EQUALS expression','sentence',3,'p_sentence','sdt_final_2.py',105),
  ('sentence -> ID','sentence',1,'p_sentence','sdt_final_2.py',106),
  ('expression -> expression PLUS expression','expression',3,'p_expression_add','sdt_final_2.py',156),
  ('expression -> expression MULT expression','expression',3,'p_expression_mult','sdt_final_2.py',161),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','sdt_final_2.py',165),
  ('expression -> expression DIV expression','expression',3,'p_expression_divide','sdt_final_2.py',169),
  ('expression -> OPBR expression CLBR','expression',3,'p_expression_brackets','sdt_final_2.py',173),
  ('expression -> ID','expression',1,'p_expression','sdt_final_2.py',178),
  ('sentence -> IF boo','sentence',2,'p_if','sdt_final_2.py',188),
  ('boo -> boo RELOP boo','boo',3,'p_relop','sdt_final_2.py',198),
  ('boo -> ID','boo',1,'p_relop','sdt_final_2.py',199),
  ('sentence -> WHILE boo','sentence',2,'p_while','sdt_final_2.py',207),
]
